system:
    services:
        #ENC[AES256_GCM,data:mXpegTNuP9XmxpYC0hfcNiNUk8xAdipAMX732T9Jid/FPC0zVFL218DmG6R3zOpiig2lcYoLOR4qnIa60P1DcWAmPII9/Se21CnMGw==,iv:kq22F3tFK9wTg7Ed35CxPTuubvOrsLIIJ+dDnAi3U4w=,tag:z5XuVHfr0/N5/eQfSinCig==,type:comment]
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:fiSwWFm8uv6E1GpIkVN8abyqAdfoXyuRzoyxI0aEpM/yQRVQggrAzKWWz+LJHDugSxykbNaX93U15oaW9d2fQcsHMpWdLxms57Ya5FXU/CJNvd3+1uplxACvNi7QqdS0lw==,iv:tR2z+h5CpJgjxlaTe+lzet5fe1xnfLjXGtWnmUAVsVk=,tag:o+J9vNRdCXe2XeMBUJRr4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lj5vmr02qkudvv2xedfj5tq8x93gllgpr6tzylwdlt7lud4tfv5qfqsd5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZkczWXBMcGc2dHNxZ1Vh
            SkxSL2VBYVBaNEQ1aENmOXhSRy90ZFBPY0dRCkxndmZERWE2SU12bmlxa25RYjVi
            aTA0K1NHNDI5WWFOK1FSVTE2bFpCeEEKLS0tIHU2U2pmcDl2dzBiVkUrbkhaT0Na
            Nm5GeW9FaEQ4eHk1cmtiRVduM0plMWMK3qUVsUnVrLBDrNLYOQL41c7b+0LGr8as
            17TVZs57WI1rKc/76qfzLZFF8fkReaosdWAi/Xd22QT3sSGbdB5HeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17edew3aahg3t5nte5g0a505sn96vnj8g8gqse8q06ccrrn2n3uysyshu2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT2NDZWkwYk5JTjBPTFF1
            bkg1UHkzVUhsanNJQ1JqWFNoTnRHcERFeTAwClE0dURzMWsvWm1VWm43SHhoM0xo
            TTNtalB3NUZLZER1NGlxemFHYWtpU0kKLS0tIDZUNjQxaVBsUEUrRDZmOVNBZmNU
            RFp1THRpMjVldzBIZ0ZKU3BLYWh6RUEKR2ytHFfuHllKTdXwgFDPxMGZW+IFTn+v
            4kuN/lkMyIHZ5OvC3XdJWKDmMuWYKXH0skuYwbNxdfGFf74CdoHWEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u4tht685sqg6dkmjyer96r93pl425u6353md6fphpd84jh3jwcusvm7mgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdXJIWUxCS3ZQT1FXUnZG
            QWp2THJxa2hWbWI0aUxBZy96YXMxakNOWDFjCmdvbXVuOW9tUk90dDNQdk1LTWtQ
            b2FtZlprSHQ3K1VmSFg5cFQxZThrazAKLS0tIEhTRC9sL2FQZlNPUmM4dVNNWnRP
            RHNCN245dllyWEdFMDlHZzlWZkpMcUUKBWDjiraPOddl8Xm7ADTyH0tgbCGQnGSy
            iJjPidPAtqfWLlqHeqJM7UAmAuniZV1R5AVEQujUBe2iVz/PHCqeUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cp6vegrmqfkuj8nmt2u3z0sur7n0f7e9x9zmdv4zygp8j2pnucpsdkgagc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcFIwQTdOb3lKRC9KeTBz
            NmtodUJDUGRJaFhqN000bkdBUm9iQnk0T1g4CnJELzF1TTJTNlEvWkV4aGpKM29U
            WUxPRFh2WHJrUHBuUm1BcnRaVEc0LzAKLS0tIFF6eGd0enBwbFRXaGpGS01yemc1
            T3ZjRW5INmFteUIyWXl1ZkR1QnNyS1UKrHgzRqQZ4iabdKcTutRNtp6KFRI7MCF8
            ahn98v+Ji38ANfBTegJXLvJPlYSEVjXpDsCImudp2KfFsrsTAhadEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j2r8mypw44uvqhfs53424h6fu2rkr5m7asl7rl3zn3xzva9m3dcqpa97gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RHA1blBVRUhneTJBZ0d3
            NU5DMDJZdWlPZVlIbTdRMWdDRlhBQUQvVEI4CnNsaHlDMkRLczNXSW5LemV2amhK
            b0FwUXVUZTY4WFZ2eXhaZDk5bGlNbVkKLS0tIHorLzdEanJjb1F6TnBkNk02MGkv
            MzZVOEFYeDlucnZSRGJHeE5BdUZEL0UKRi1Y9TTstpWci22wtVaguuJ6kF9puFwA
            HMUFtR1ER7KXvJT634Eg11eex+Mg3Xl71BReJMvCxs9aTP9hhzQXSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ya4sddch9mqxzs7tk8xkxat52mrjatuafylzyw5urgat4869f9asjfvqfy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTGh3YjE3eTNEN3lCR1FE
            MWhvUy9uVGVmcC83ZE5uQmM1WFZ3UllUWjNRCmtYa2ZBVWtmZDBQWTErWGF1a3Bp
            ZEx0U0ExNDNRZ0lzZmh0ajcvak5YSmsKLS0tIFlZUnAzbXZSbVJrNGtZRkdFaXNq
            cFJUNEM4Wjd3bGF3MmV5TEhyWVVlRVUKzZFh40978hlHc9eaHZFUdXfvjcrRL4R1
            IoG/tPNeTXv8TJ9aePls9ZjMSlAxXQfS+lBDHxFRee2fCIsJ1mbW6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T11:18:32Z"
    mac: ENC[AES256_GCM,data:I/q/534ZRkxy+WLCbY8BSjMtpEcpbANk3xZBG1pWvrEErw6MNQIQQbkV21rnxv5yOkr0VLVul4rwj1ELOVj5Y8W4LkVB/g95xt5GA3u+Mi/RPnGfMHTR+LNpXqMZc3Id9QvEsukwlC5NzQTUnsJBQ8e8EHXKr7HNhKX5bhLCGbU=,iv:QD2QyFlqTBRXRZIfOT7CwyIg2iBxVen8Ga8w1fNy0Xw=,tag:0IzGRj/zQ9S5sLTJmqvWlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
